### ISSUE TITLE
Duplicate sea labels near Venice

### ISSUE THREAD

**Issue by nvkelso** [tilezen/vector-datasource#953]
* **What did you see?** Adriatic, Adriatic, Adriatic in every single tile
* **What did you expect to see?** Just one, or a couple but spaced out more than 1 tile apart.
* **What map location are you having problems with?** Near Venice.
* **Screenshot?** 

<img width="983" alt="screen shot 2016-08-09 at 10 12 43" src="https://cloud.githubusercontent.com/assets/853051/17531929/f72d5940-5e32-11e6-8bf8-6e5a638de890.png">

**Comment by zerebubuth** [comment]
I just checked dev, and it looks like that label is no longer present, nor is the sea polygon which might have been generating it client side. Has this been fixed by #951 and/or #965?

**Comment by rmarianski** [comment]
Yea, I think we introduced this when we added sea polygons, and believe #951 would be the fix. Dev currently matches prod, at least for the next couple of days or so. We should re-verify when we deploy again to dev.

**Comment by nvkelso** [comment]
Verified no longer dup labels (and that we still have a single label for the sea).
